# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: BizPlace

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    mail:
        host: smtp.gmail.com
        user: backup@quador.ro
        port: 587
        password: quadorBackup02
        protocol: smtp
        tls: true
        auth: true
        from: backup@quador.ro

    messageSource:
        cacheSeconds: 1

swagger:
    title: BizPlace API
    description: BizPlace applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
